my_flask_app/app/routes.py
# app/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from .model import DataSQL, DataMember
from . import db
import pandas as pd
import io
import chardet
from sqlalchemy import text
import math

main_bp = Blueprint('main', __name__)

@main_bp.route('/')
def index():
    datasql = DataSQL.query.all()
    datamember = DataMember.query.all()
    return render_template('index.html', datasql=datasql, datamember=datamember)

@main_bp.route('/upload', methods=['POST'])
def upload():
    if 'file_sql' not in request.files and 'file_member' not in request.files:
        flash('Please select either SQL or Member file.')
        return redirect(url_for('main.index'))

    try:
        # Process SQL file
        if 'file_sql' in request.files:
            file_sql = request.files['file_sql']

            # Detect encoding using chardet
            sql_encoding = chardet.detect(file_sql.read())['encoding']

            # If encoding is not detected, use a default encoding (you can change 'utf-8' to another encoding)
            if sql_encoding is None:
                sql_encoding = 'utf-8'

            # Reset file cursor to the beginning
            file_sql.seek(0)

            # Read SQL file using pandas with detected encoding and ';' as separator
            if file_sql.filename.endswith('.csv'):
                df_sql = pd.read_csv(io.StringIO(file_sql.read().decode(sql_encoding)), sep='\t', engine='python', skiprows=range(1, 5))
            elif file_sql.filename.endswith('.xlsx'):
                df_sql = pd.read_excel(io.BytesIO(file_sql.read()), engine='openpyxl')
            else:
                flash('Unsupported file format for SQL file. Please use CSV or XLSX.')
                return redirect(url_for('main.index'))

            # Iterate over each row in the DataFrame for DataSQL
            for idx, row in df_sql.iterrows():
                try:
                    data_sql = DataSQL(
                        tgl=row['TGL'],
                        rrn=row['RRN'],
                        response_code=row['RESPONSE_CODE'],
                        proc_code=row['PROC_CODE'],
                        acq_bank_nama=row['ACQ_BANK_NAMA'],
                        iss_bank_nama=row['ISS_BANK_NAMA'],
                        merchant_name_location=row['MERCHANT_NAME_LOCATION'],
                        trx_amount=row['TRX_AMOUNT']
                    )
                    db.session.add(data_sql)
                except Exception as e:
                    flash(f"Error processing SQL file, row {idx + 2}: {str(e)}")
                    print(f"Error processing SQL file, row {idx + 2}: {str(e)}")  # Debugging print
                    continue

        # Process Member file
        if 'file_member' in request.files:
            file_member = request.files['file_member']

            # Detect encoding using chardet
            member_encoding = chardet.detect(file_member.read())['encoding']

            # If encoding is not detected, use a default encoding (you can change 'utf-8' to another encoding)
            if member_encoding is None:
                member_encoding = 'utf-8'

            # Reset file cursor to the beginning
            file_member.seek(0)

            # Read Member file using pandas with detected encoding and ';' as separator
            if file_member.filename.endswith('.csv'):
                df_member = pd.read_csv(io.StringIO(file_member.read().decode(member_encoding)), sep=';', engine='python', skiprows=range(1, 5))
            elif file_member.filename.endswith('.xlsx'):
                df_member = pd.read_excel(io.BytesIO(file_member.read()), engine='openpyxl')
            else:
                flash('Unsupported file format for Member file. Please use CSV or XLSX.')
                return redirect(url_for('main.index'))

            # Print header and first 5 rows of the DataFrame for debugging
            print("Member File Header:", df_member.columns.tolist())
            print("Member File Data:")
            print(df_member.head())  # Print the first 5 rows


            # Debugging: Print data types of each column in DataFrame for Member
            print("Data Types:")
            print(df_member.dtypes)

            # Iterate over each row in the DataFrame for DataMember
            for idx, row in df_member.iterrows():
                try:
                    data_member = DataMember(
                        tgl=row['TGL'],
                        id=row['ID'],
                        id_trx=row['ID_TRX'],
                        transaction_date=row['TRANSACTION_DATE'],
                        transaction_time=row['TRANSACTION_TIME'],
                        response_code=row['RESPONSE_CODE'],
                        rrn=row['RRN'],
                        proc_code=row['PROC_CODE'],
                        acq_bank_code=row['ACQ_BANK_CODE'],
                        nama_acq=row['NAMA'],
                        id_principal_acq=row['ID_PRINCIPAL'],
                        iss_bank_code=row['ISS_BANK_CODE'],
                        nama_iss=row['NAMA'],
                        id_principal_iss=row['ID_PRINCIPAL'],
                        pan=row['PAN'],
                        acc_identification=row['ACC_IDENTIFICATION'],
                        merchant_name_location=row['MERCHANT_NAME_LOCATION'],
                        trx_amount=int(row['TRUNCATE(TRX_AMOUNT,0)']),
                        request=row['REQUEST']
                    )
                    db.session.add(data_member)
                except Exception as e:
                    flash(f"Error processing Member file, row {idx + 2}: {str(e)}")
                    print(f"Error processing Member file, row {idx + 2}: {str(e)}")  # Debugging print
                    continue

        db.session.commit()
        flash('Files uploaded successfully and data inserted into the database.')
    except Exception as e:
        flash(f'Error processing files: {str(e)}')
        print(f'Error processing files: {str(e)}')  # Debugging print

    return redirect(url_for('main.index'))




def get_paginated_results(page, page_size, status):
    offset = (page - 1) * page_size

    query = text("""WITH NoHaveSuccess AS (
    SELECT DISTINCT rrn
    FROM data_sql
    UNION
    SELECT DISTINCT rrn
    FROM data_member
    EXCEPT
    SELECT DISTINCT rrn
    FROM data_sql
    INTERSECT
    SELECT DISTINCT rrn
    FROM data_member
),
NoHaveSQL AS (
    SELECT DISTINCT rrn
    FROM data_member
    EXCEPT
    SELECT DISTINCT rrn
    FROM data_sql
),
NoHaveMember AS (
    SELECT DISTINCT rrn
    FROM data_sql
    EXCEPT
    SELECT DISTINCT rrn
    FROM data_member
)
SELECT 
    tgl,
    rrn,
    merchant_name_location_sql,
    response_code_sql,
    acq_bank_code_sql,
    nama_iss_sql,
    trx_amount_sql,
    merchant_name_location_member,
    response_code_member,
    acq_bank_code_member,
    nama_iss_member,
    trx_amount_member,
    rrn_sql,
    rrn_member,
    rrn_source,
    CASE 
        WHEN overall_status = 'Success' THEN 'Success'
        WHEN overall_status = 'Have SQL' THEN 'Have SQL'
        WHEN overall_status = 'Have Member' THEN 'Have Member'
    END AS status,
    COUNT(*) OVER () AS total_sukses_rrn,
    COUNT(*) OVER (PARTITION BY overall_status) AS total_transaksi_success,
    (SELECT COUNT(DISTINCT rrn) FROM NoHaveSuccess) AS no_have_success,
    (SELECT COUNT(DISTINCT rrn) FROM NoHaveSQL) AS no_have_sql,
    (SELECT COUNT(DISTINCT rrn) FROM NoHaveMember) AS no_have_member
FROM (
    SELECT 
        COALESCE(data_sql.tgl::text, data_member.tgl::text) AS tgl,
        COALESCE(data_sql.rrn, data_member.rrn) AS rrn,
        COALESCE(data_sql.merchant_name_location, '') AS merchant_name_location_sql,
        COALESCE(data_sql.response_code, '') AS response_code_sql,
        COALESCE(data_sql.acq_bank_nama, '') AS acq_bank_code_sql,
        COALESCE(data_sql.iss_bank_nama, '') AS nama_iss_sql,
        COALESCE(CAST(data_sql.trx_amount AS INTEGER), 0) AS trx_amount_sql,
        COALESCE(data_member.merchant_name_location, '') AS merchant_name_location_member,
        COALESCE(data_member.response_code, '') AS response_code_member,
        COALESCE(data_member.acq_bank_code, '') AS acq_bank_code_member,
        COALESCE(data_member.nama_iss, '') AS nama_iss_member,
        COALESCE(CAST(data_member.trx_amount AS INTEGER), 0) AS trx_amount_member,
        COALESCE(data_sql.rrn, '') AS rrn_sql,
        COALESCE(data_member.rrn, '') AS rrn_member,
        CASE 
            WHEN data_sql.rrn IS NOT NULL AND data_member.rrn IS NOT NULL THEN 'Success'
            WHEN data_sql.rrn IS NOT NULL THEN 'Have SQL'
            WHEN data_member.rrn IS NOT NULL THEN 'Have Member'
        END AS rrn_source,
        CASE 
            WHEN data_sql.rrn IS NOT NULL AND data_member.rrn IS NOT NULL THEN 'Success'
            WHEN data_sql.rrn IS NOT NULL THEN 'Have SQL'
            WHEN data_member.rrn IS NOT NULL THEN 'Have Member'
        END AS overall_status
    FROM data_sql
    FULL OUTER JOIN data_member ON data_sql.rrn = data_member.rrn
) AS subquery
WHERE overall_status = :status
ORDER BY rrn_source, rrn, overall_status
LIMIT :page_size OFFSET :offset;





    """)


    

    # Menambahkan parameter page dan page_size
    results = db.session.execute(query, {'status': status, 'page_size': page_size, 'offset': offset, 'page': page})
    results_list = results.fetchall()

    return results_list





@main_bp.route('/show_results', methods=['POST'])
def show_results():
    status = request.form.get('status')
    if not status:
        flash('Please select a status.')
        return redirect(url_for('main.index'))

    # Menambahkan validasi status untuk pilihan yang diinginkan
    allowed_statuses = ['Success', 'Have Member', 'Have SQL', 'No Have SQL', 'No Have Member', 'No Have Success']
    if status not in allowed_statuses:
        flash('Invalid status selected.')

my_flask_app/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Show Results</title>
    <style>
      #pagination {
        margin-top: 10px;
      }

      #prevBtn,
      #nextBtn {
        margin-right: 5px;
      }

      .result-container {
        display: flex;
        justify-content: space-around;
      }

      .result-item {
        text-align: center;
        border: 2px;
      }
    </style>
  </head>

  <body>
    <h1>Show Results</h1>

    {% with messages = get_flashed_messages() %} {% if messages %}
    <ul>
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %} {% endwith %}

    <!-- Upload Data Form -->
    <form
      action="{{ url_for('main.upload') }}"
      method="post"
      enctype="multipart/form-data"
    >
      <label for="sql_file">Upload Data SQL:</label>
      <input type="file" name="file_sql" accept=".xlsx, .xls" />
      <br />

      <label for="member_file">Upload Data Member:</label>
      <input type="file" name="file_member" accept=".xlsx, .xls" />
      <br />

      <input type="submit" value="Upload" />
    </form>

    <hr />

    <!-- Select Status Form -->
    <form
      action="{{ url_for('main.show_results') }}"
      method="post"
      id="statusForm"
    >
      <label for="status">Select Status:</label>
      <select name="status" id="statusSelect">
        <option value="" disabled selected>Select a Status</option>
        <option value="Success">Success</option>
        <option value="Have Member">Have Member</option>
        <option value="Have SQL">Have SQL</option>
      </select>
      <button type="submit">Show Results</button>
    </form>

    <!-- Displaying Results -->
    {% if results_list %}
    <h1>{{ result_heading }}</h1>

    <ul>
      <li>
        <b>NoHaveSuccess:</b> Jumlah rrn yang muncul di data_sql atau
        data_member, tetapi tidak dalam kedua tabel(Tidak ada yang sama rrn dari
        kedua tabel).
      </li>
      <li>
        <b>NoHaveSQL:</b> Jumlah rrn yang muncul di data_member, tetapi tidak
        dalam data_sql.
      </li>
      <li>
        <b>NoHaveMember:</b> Jumlah rrn yang muncul di data_sql, tetapi tidak
        dalam data_member.
      </li>
    </ul>

    <table border="1">
      <thead>
        <tr>
          <th>Total RRN</th>
          <th>Total TRX</th>
          <!-- Kolom baru yang ditambahkan -->
          <th>No Have Success</th>
          <th>No Have SQL</th>
          <th>No Have Member</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{ total_sukses_rrn }}</td>
          <td>{{ total_transaksi_success }}</td>
          <!-- Isi kolom baru dengan nilai yang sesuai -->
          <td>
            {% if results_list[0].no_have_success %}{{
            results_list[0].no_have_success }}{% endif %}
          </td>
          <td>
            {% if results_list[0].no_have_sql %}{{ results_list[0].no_have_sql
            }}{% endif %}
          </td>
          <td>
            {% if results_list[0].no_have_member %}{{
            results_list[0].no_have_member }}{% endif %}
          </td>
        </tr>
      </tbody>
    </table>

    <table border="1">
      <thead>
        <tr>
          <th>TGL</th>
          <th>RRN</th>
          <th>Merchant Name Location (SQL)</th>
          <th>Response Code (SQL)</th>
          <th>Acq Bank Code (SQL)</th>
          <th>Nama ISS (SQL)</th>
          <th>Trx Amount (SQL)</th>
          <th>Merchant Name Location (Member)</th>
          <th>Response Code Member</th>
          <th>Acq Bank Code Member</th>
          <th>Nama ISS Member</th>
          <th>Trx Amount Member</th>
          <th>RRN SQL</th>
          <th>RRN Member</th>
          <th>RRN Source</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody id="resultsTableBody">
        {% for result in results_list %}
        <tr>
          <td>{{ result.tgl }}</td>
          <td>{{ result.rrn }}</td>
          <td>{{ result.merchant_name_location_sql }}</td>
          <td>{{ result.response_code_sql }}</td>
          <td>{{ result.acq_bank_code_sql }}</td>
          <td>{{ result.nama_iss_sql }}</td>
          <td>{{ result.trx_amount_sql }}</td>
          <td>{{ result.merchant_name_location_member }}</td>
          <td>{{ result.response_code_member }}</td>
          <td>{{ result.acq_bank_code_member }}</td>
          <td>{{ result.nama_iss_member }}</td>
          <td>{{ result.trx_amount_member }}</td>
          <td>{{ result.rrn_sql }}</td>
          <td>{{ result.rrn_member }}</td>
          <td>{{ result.rrn_source }}</td>
          <td>{{ result.status }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <div id="pagination">
      <button id="prevBtn" onclick="changePage(-1)">Previous</button>
      <button id="nextBtn" onclick="changePage(1)">Next</button>
    </div>

    {% endif %}

    <script>
        let currentPage = 1;
        const resultsPerPage = 10; // Sesuaikan jumlah data per halaman
        let resultsList = {
            {
                results_list | tojson
            }
        };
        const totalResults = resultsList.length;

        let noHaveSQLCount = 0;
        let noHaveMemberCount = 0;
        let noHaveSuccessCount = 0;

        function calculateNoHaveCounts() {
            noHaveSQLCount = resultsList.filter(result => result.status === 'No Have SQL').length;
            noHaveMemberCount = resultsList.filter(result => result.status === 'No Have Member').length;
            noHaveSuccessCount = resultsList.filter(result => result.status === 'No Have Success').length;
        }

        function showResultsOnPage(page) {
            const startIdx = (page - 1) * resultsPerPage;
            const endIdx = startIdx + resultsPerPage;
            const pageResults = resultsList.slice(startIdx, endIdx);

            const tableBody = document.getElementById("resultsTableBody");
            tableBody.innerHTML = "";

            for (const result of pageResults) {
                const row = document.createElement("tr");
                row.innerHTML = `<td>${result.tgl}</td>
      <td>${result.rrn}</td>
      <td>${result.merchant_name_location_sql}</td>
      <td>${result.response_code_sql}</td>
      <td>${result.acq_bank_code_sql}</td>
      <td>${result.nama_iss_sql}</td>
      <td>${result.trx_amount_sql}</td>
      <td>${result.merchant_name_location_member}</td>
      <td>${result.response_code_member}</td>
      <td>${result.acq_bank_code_member}</td>
      <td>${result.nama_iss_member}</td>
      <td>${result.trx_amount_member}</td>
      <td>${result.rrn_sql}</td>
      <td>${result.rrn_member}</td>
      <td>${result.rrn_source}</td>
      <td>${result.status}</td>`;

                tableBody.appendChild(row);
            }

            calculateNoHaveCounts();
            updateNoHaveCounts();
        }

        function updateNoHaveCounts() {
            document.getElementById("noHaveSQLCount").textContent = noHaveSQLCount;
            document.getElementById("noHaveMemberCount").textContent = noHaveMemberCount;
            document.getElementById("noHaveSuccessCount").textContent = noHaveSuccessCount;
        }

        function changePage(delta) {
            currentPage += delta;
            if (currentPage < 1) {
                currentPage = 1;
            } else if (currentPage > calculateTotalPages()) {
                currentPage = calculateTotalPages();
            }

            showResultsOnPage(currentPage);
        }

        function calculateTotalPages() {
            return Math.ceil(totalResults / resultsPerPage);
        }

        document.getElementById("pagination").style.display = "none";

        document.getElementById("statusForm").addEventListener("submit", function(event) {
            event.preventDefault();

            const selectedStatus = document.getElementById("statusSelect").value;

            // Update the result title based on the selected status
            const resultTitle = document.getElementById("resultTitle");
            resultTitle.textContent = `Results ${selectedStatus}`;

            fetchResults(selectedStatus);
        });

        function fetchResults(status) {
            // Fetch results using the selected status
            const formData = new FormData(document.getElementById("statusForm"));
            formData.set("status", status);

            fetch("/show_results", {
                    method: "POST",
                    body: formData,
                })
                .then(response => response.json())
                .then(data => {
                    resultsList = data.results_list;
                    showResultsOnPage(currentPage);
                    document.getElementById("pagination").style.display = "block";
                })
                .catch(error => console.error("Error fetching results:", error));
        }
    </script>
  </body>
</html>

my_flask_app/app/templates/results.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Show Results</title>
    <style>
      #pagination {
        margin-top: 10px;
      }

      #prevBtn,
      #nextBtn {
        margin-right: 5px;
      }

      .result-container {
        display: flex;
        justify-content: flex-start;
      }

      .result-item {
        text-align: center;
      }

      .pagination button {
        cursor: pointer;
        padding: 5px 10px;
        margin: 0 2px;
        border: 1px solid #ddd;
        border-radius: 4px;
      }

      .pagination button.active {
        background-color: #4caf50;
        color: white;
        border: 1px solid #4caf50;
      }
    </style>
  </head>

  <body>
    <h1>Show Results</h1>

    {% with messages = get_flashed_messages() %} {% if messages %}
    <ul>
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %} {% endwith %}

    <!-- Upload Data Form -->
    <form
      action="{{ url_for('main.upload') }}"
      method="post"
      enctype="multipart/form-data"
    >
      <label for="sql_file">Upload Data SQL:</label>
      <input type="file" name="file_sql" accept=".xlsx, .xls" />
      <br />

      <label for="member_file">Upload Data Member:</label>
      <input type="file" name="file_member" accept=".xlsx, .xls" />
      <br />

      <input type="submit" value="Upload" />
    </form>

    <hr />

    <!-- Select Status Form -->
    <form
      action="{{ url_for('main.show_results') }}"
      method="post"
      id="statusForm"
    >
      <label for="status">Select Status:</label>
      <select name="status" id="statusSelect">
        <option value="" disabled selected>Select a Status</option>
        <option value="Success">Success</option>
        <option value="Have Member">Have Member</option>
        <option value="Have SQL">Have SQL</option>
      </select>
      <button type="submit">Show Results</button>
    </form>

    <!-- Displaying Results -->
    {% if results_list %}
    <h1>Results</h1>

    <div class="result-container">
      <div class="result-item">
        <h4>Total RRN</h4>
        <h5>{{ total_sukses_rrn }}</h5>
      </div>

      <div class="result-item">
        <h4>Total TRX</h4>
        <h5>{{ total_transaksi_success }}</h5>
      </div>
    </div>

    <table border="1">
      <thead>
        <tr>
          <th>TGL</th>
          <th>RRN</th>
          <th>Merchant Name Location (SQL)</th>
          <th>Response Code (SQL)</th>
          <th>Acq Bank Code (SQL)</th>
          <th>Nama ISS (SQL)</th>
          <th>Trx Amount (SQL)</th>
          <th>Merchant Name Location (Member)</th>
          <th>Response Code Member</th>
          <th>Acq Bank Code Member</th>
          <th>Nama ISS Member</th>
          <th>Trx Amount Member</th>
          <th>RRN SQL</th>
          <th>RRN Member</th>
          <th>RRN Source</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody id="resultsTableBody">
        {% for result in results_list %}
        <tr>
          <td>{{ result.tgl }}</td>
          <td>{{ result.rrn }}</td>
          <td>{{ result.merchant_name_location_sql }}</td>
          <td>{{ result.response_code_sql }}</td>
          <td>{{ result.acq_bank_code_sql }}</td>
          <td>{{ result.nama_iss_sql }}</td>
          <td>{{ result.trx_amount_sql }}</td>
          <td>{{ result.merchant_name_location_member }}</td>
          <td>{{ result.response_code_member }}</td>
          <td>{{ result.acq_bank_code_member }}</td>
          <td>{{ result.nama_iss_member }}</td>
          <td>{{ result.trx_amount_member }}</td>
          <td>{{ result.rrn_sql }}</td>
          <td>{{ result.rrn_member }}</td>
          <td>{{ result.rrn_source }}</td>
          <td>{{ result.status }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <div class="pagination" id="pagination">
      <button id="prevBtn" onclick="changePage(-1)">Previous</button> {% for
      page in range(1, total_pages + 1) %}
      <button
        onclick="changePage({{ page }})"
        class="{{ 'active' if page == current_page else '' }}"
      >
        {{ page }}
      </button>
      {% endfor %}
      <button id="nextBtn" onclick="changePage(1)">Next</button>
    </div>

    {% endif %}
    <script>
        let currentPage = 1;
        const resultsPerPage = 10;
        let resultsList = {
            {
                results_list | tojson
            }
        };
        const totalResults = resultsList.length;
        const total_pages = Math.ceil(totalResults / resultsPerPage);

        function calculateTotalPages() {
            return Math.ceil(totalResults / resultsPerPage);
        }

        function showResultsOnPage(page) {
            const startIdx = (page - 1) * resultsPerPage;
            const endIdx = startIdx + resultsPerPage;
            const pageResults = resultsList.slice(startIdx, endIdx);

            const tableBody = document.getElementById("resultsTableBody");
            tableBody.innerHTML = "";

            for (const result of pageResults) {
                const row = document.createElement("tr");
                row.innerHTML = `<td>${result.tgl}</td>
      <td>${result.rrn}</td>
      <td>${result.merchant_name_location_sql}</td>
      <td>${result.response_code_sql}</td>
      <td>${result.acq_bank_code_sql}</td>
      <td>${result.nama_iss_sql}</td>
      <td>${result.trx_amount_sql}</td>
      <td>${result.merchant_name_location_member}</td>
      <td>${result.response_code_member}</td>
      <td>${result.acq_bank_code_member}</td>
      <td>${result.nama_iss_member}</td>
      <td>${result.trx_amount_member}</td>
      <td>${result.rrn_sql}</td>
      <td>${result.rrn_member}</td>
      <td>${result.rrn_source}</td>
      <td>${result.status}</td>`;

                tableBody.appendChild(row);
            }
        }

        function changePage(delta) {
            currentPage += delta;
            if (currentPage < 1) {
                currentPage = 1;
            } else if (currentPage > total_pages) {
                currentPage = total_pages;
            }

            showResultsOnPage(currentPage);
        }

        // Hide pagination initially
        document.getElementById("pagination").style.display = "none";

        // Initial page load when the "Show Results" button is clicked
        document.getElementById("statusForm").addEventListener("submit", function(event) {
            event.preventDefault();
            showResultsOnPage(currentPage);
            document.getElementById("pagination").style.display = "block";
        });
    </script>
  </body>
</html>